package constants

const (
	RESPONSE_SUCCESS               = "SUCCESS"
	RESPONSE_BAD_REQUEST           = "BAD_REQUEST"
	RESPONSE_NOT_FOUND             = "NOT_FOUND"
	RESPONSE_TOO_MANY_REQUESTS     = "TOO_MANY_REQUESTS"
	RESPONSE_UNAUTHORIZED          = "UNAUTHORIZED"
	RESPONSE_UNAUTHENTICATED       = "UNAUTHENTICATED"
	RESPONSE_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
)
